/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://hmzgc5hjpvamzotg75gv3b7eo4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pwc7cqqxgvdlvat57wgra5a6bm"
};


export default awsconfig;
